### ISSUE TITLE
Segment filtering by "Provider -is not- unknown" not possible

### ISSUE THREAD

**Issue by hpvd** [matomo-org/matomo#10312]
Segment filtering by "Provider -is not- unknown" not possible.
Should work for entering
1) nothing (leaving field empty)
2) word "unknown"

"1)" is the way it works to filter only visits where it was possible to receive a keyword from search engine

![2016-07-15_16h38_19](https://cloud.githubusercontent.com/assets/5681880/16877925/b9147eb8-4aaa-11e6-8bcf-4b22ca1cf4ea.png)

**Comment by tsteur** [comment]
Thx for creating the issue 👍

**Comment by colorando-de** [comment]
Any progress on this issue? I want to exclude the Sistrix crawler which has an unkown OS and unknown browser.

**Comment by sgiehl** [comment]
Just tried to reproduce, but for me creating the segment as mentioned above has the correct result.
Can anyone else confirm this is fixed?

**Comment by hpvd** [comment]
when applying segment "provider" "is not" "unknown" in visitor log page,
visitis with provider "unknown" are still shown...

**Comment by hpvd** [comment]
same for "provider" "is not" ""
![2017-09-10_23h06_43](https://user-images.githubusercontent.com/5681880/30253014-d4a34f3c-967c-11e7-94a9-53c9d28a2280.png)
