### ISSUE TITLE
logo.svg not found

### ISSUE THREAD

**Issue by courtens** [matomo-org/matomo#12623]
OK - this is an old issue (https://github.com/matomo-org/matomo/issues/11765), but here it is again.

**Comment by halfer** [comment]
I believe the other bug was fixed, and my own experience is that the issue went away. Is this a new occurrence of the same bug?

**Comment by courtens** [comment]
it wasn't fixed (it never went away.) I gave up on bugging for it...

**Comment by mattab** [comment]
Hi @courtens 

Is your matomo installed behind a proxy and in a sub-path? If so, see the new FAQ section:

![important](https://user-images.githubusercontent.com/466765/38001523-b08055ce-3289-11e8-8e6b-d118f7e63cb2.png)

in https://matomo.org/faq/how-to-install/faq_98/

**Comment by sgiehl** [comment]
should have been fixed with https://github.com/matomo-org/matomo/pull/16341
If anyone still has a similar issue, feel free to create a new report. Thanks.
