### ISSUE TITLE
Entry “Piwik\Auth” cannot be resolved after update to 3.6.0-b4

### ISSUE THREAD

**Issue by froger-me** [matomo-org/matomo#13270]
After updating to 3.6.0-b4, visiting the index shows:

`Entry “Piwik\Auth” cannot be resolved: the class is not instantiableFull definition:Object ( class = #NOT INSTANTIABLE# Piwik\Auth scope = singleton lazy = false)`

The issue is I cannot downgrade back to 3.6.0-b3 (database backup failed).

Could you please indicate either:
- the steps (SQL queries) to downgrade the database manually back to 3.6.0-b3
- a manual quickfix of the 3.6.0-b4 code base

... to (at least) get Matomo back up and running after upgrade to 3.6.0-b4?

**Comment by froger-me** [comment]
Downgraded to 3.6.0-b1 to get the issue go away

**Comment by sgiehl** [comment]
@froger-me  do you have any third party plugins installed like Google Authenticator?

**Comment by froger-me** [comment]
Now that you mention it...

Bandwidth (v3.1.1)
CustomDimensions (v3.1.3)
ExampleRssWidget (v1.0)
LoginLdap (v4.0.5)
PiwikPro (v3.6.0-b1)
VisitorAvatar (v0.2.2)
BotTracker (v1.02)

**Comment by sgiehl** [comment]
Guess that might be caused by LoginLdap then...

**Comment by froger-me** [comment]
@diosmosis Hi - I am sorry, the install I am maintaining is in a production environment (and yes, beta updates were enabled and that was not really my decision). I have recommended not to have it enabled anymore, as it is imperative we get no downtime.

**Comment by diosmosis** [comment]
@froger-me I see, if you experience the same problem later in a staging environment, let us know.

**Comment by diosmosis** [comment]
These changes should fix this issue: https://github.com/matomo-org/matomo/pull/13279

**Comment by XinfinityoO** [comment]
issue still in beta 5 reverted back to beta 1. has the changes been merged yet ??

**Comment by sgiehl** [comment]
https://github.com/matomo-org/matomo/pull/13279 has not yet been merged. But you could test it by applying the changed manually after updating

**Comment by minusf** [comment]
this seems to be still broken in 3.9.1.  when the Ldap plugin is enabled, the cronjob core archive fails:

```
ERROR [2019-06-06 14:54:55] 86394  There was an error while regenerating container releases: Entry "Piwik\Auth" cannot be resolved: the class is not instantiable
Full definition:
Object (
    class = #NOT INSTANTIABLE# Piwik\Auth
    scope = singleton
    lazy = false
)#0 /export/matomo/vendor/php-di/php-di/src/DI/Definition/Resolver/ObjectCreator.php(243): DI\Definition\Exception\DefinitionException::create(Object(DI\Definition\ObjectDefinition), 'Entry "Piwik\\Au...')
```

any reason why this is closed if not merged?
