### ISSUE TITLE
WARNING: Trying to add two strings in DataTable\Row::sumRowArray

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#13839]
just updated demo.matomo.org to beta4 and now getting heaps of warning like: `WARNING: Trying to add two strings in DataTable\Row::sumRowArray: 0 + -58.4% for row # ['nb_visits' =&gt; 84389, 'nb_actions' =&gt; 302230, 'Actions_nb_pageviews' =&gt; 132551, 'Goal_revenue' =&gt; 1462.6, 'Goal_nb_conversions' =&gt; 5628, 'Goal_0_nb_conversions' =&gt; 0, 'Goal_0_revenue' =&gt; 0, 'label' =&gt; -2, 'visits_evolution' =&gt; 0, 'actions_evolution' =&gt; 0, 'pageviews_evolution' =&gt; 0, 'revenue_evolution' =&gt; 0, 'nb_conversions_evolution' =&gt; 0, 'orders_evolution' =&gt; 0, 'ecommerce_revenue_evolution' =&gt; 0, 'nb_pageviews' =&gt; 98667, 'revenue' =&gt; 307868.6, 'nb_conversions' =&gt; 3849, 'orders' =&gt; 1557, 'ecommerce_revenue' =&gt; 305945.6] [] [idsubtable = ]&lt;br /&gt; `

can be visible at: https://demo.matomo.org/index.php?module=TagManager&action=manageContainers&idSite=62&period=day&date=yesterday

it looks like this:
![screenshot from 2018-12-13 10-23-10](https://user-images.githubusercontent.com/466765/49899627-1c324580-fec1-11e8-8b4f-8c192c2160e3.png)

**Comment by tsteur** [comment]
@diosmosis I've debugged locally and looked into code and then temporarily disabled proxysite on demo and then the error occurred. It can be reproduced on https://demo.matomo.org/index.php?module=MultiSites&action=index&idSite=1&period=day&date=yesterday when ProxySite is enabled. I think we have fixed this issue in https://github.com/matomo-org/matomo/pull/13853 already? The patch is now applied on the demo instance but still seems to occur?

**Comment by tsteur** [comment]
Just to be sure as I think you mentioned it before in chat. Should I apply the whole Reports Total calculator patch on the demo so the totals row will be returned and won't be processed again?

**Comment by tsteur** [comment]
Applied the patch and it is now fixed. Can reload https://demo.matomo.org/index.php?module=MultiSites&action=index&idSite=62&period=day&date=yesterday as often as I want but does not appear anymore.

**Comment by mattab** [comment]
I'm still seeing the warnings on the demo which is running 3.8.0-rc2:

> From 2019-01-07 to 2019-01-13
> WARNING: Trying to add two strings in DataTable\Row::sumRowArray: 0 + 33% for row # ['label' =&gt; -2, 'nb_visits' =&gt; 6093, 'nb_hits' =&gt; 11605, 'sum_time_spent' =&gt; 768459, 'nb_hits_following_search' =&gt; 35, 'nb_hits_with_time_generation' =&gt; 10819, 'min_time_generation' =&gt; 0.003, 'max_time_generation' =&gt; 55.676, 'entry_nb_visits' =&gt; 1874, 'entry_nb_actions' =&gt; 8126, 'entry_sum_visit_length' =&gt; 455983, 'entry_bounce_count' =&gt; 648, 'exit_nb_visits' =&gt; 2212, 'sum_daily_nb_uniq_visitors' =&gt; 5323, 'sum_daily_entry_nb_uniq_visitors' =&gt; 1748, 'sum_daily_exit_nb_uniq_visitors' =&gt; 2059, 'avg_time_on_page' =&gt; 0, 'bounce_rate' =&gt; 0, 'exit_rate' =&gt; 0, 'avg_time_generation' =&gt; 0] [] [idsubtable = ]&lt;br /&gt; 

* URL: https://demo.matomo.org/index.php?module=MultiSites&action=index&idSite=1&period=week&date=today


![screenshot_2019-01-09 all websites dashboard - from 2019-01-07 to 2019-01-13 - web analytics reports -](https://user-images.githubusercontent.com/466765/50866691-d9a45000-140f-11e9-8240-e224f9760d4a.png)

**Comment by mattab** [comment]
Still seeing the error on demo.matomo.org today, any idea @diosmosis ?

![screenshot from 2019-02-12 15-46-56](https://user-images.githubusercontent.com/466765/52608017-73628f80-2edd-11e9-9205-b7612f78b28f.png)

**Comment by diosmosis** [comment]
Updating demo to 3.8.1 from a rc, should fix this.
