### ISSUE TITLE
Internal site serach decoding bug

### ISSUE THREAD

**Issue by KALLIAK** [matomo-org/matomo#15060]
We have site in russian language in windows-1251 codepage and all working fine except internal site serch keywords. 

E.g. when I try to find ‘окрб’ this keyword turns to url encoded ‘q=%EE%EA%F0%E1’ and then in database it turns to some wierd encoded string ’ Г®ГЄГ°ГЎ’.

There is small 2-HTML page site (windows-1251) where the problem can be reproduced:
[test.zip](https://github.com/matomo-org/matomo/files/3770797/test.zip)

Matomo 3.11.0
Thanks!

**Comment by tsteur** [comment]
@mattab moved this to 4.1.0 as it's not a regression.

**Comment by KALLIAK** [comment]
This is how I solved problem with decoding windows-1251 url encoded string:

function urlDecodeCP1251($raw_url_encoded)
{
    $hex_table = array(
        0 => 0x00,
        1 => 0x01,
        2 => 0x02,
        3 => 0x03,
        4 => 0x04,
        5 => 0x05,
        6 => 0x06,
        7 => 0x07,
        8 => 0x08,
        9 => 0x09,
        "A" => 0x0a,
        "B" => 0x0b,
        "C" => 0x0c,
        "D" => 0x0d,
        "E" => 0x0e,
        "F" => 0x0f
    );

    if(preg_match_all("/(\%[A-Z0-9]{2})/i", $raw_url_encoded, $res)) {

        $res = array_unique($res = $res[1]);
        $arr_unicoded = array();

        foreach($res as $key => $value) {
            $hex = ($hex_table[substr($value, 1, 1)] << 4) | ($hex_table[substr($value, 2, 1)]);
            $arr_unicoded[] = urlencode(mb_convert_encoding(chr($hex), "utf-8", "windows-1251"));
        }

        $raw_url_encoded = str_replace($res, $arr_unicoded, $raw_url_encoded);
    }
               
    return urldecode($raw_url_encoded);
}

assert(urlDecodeCP1251('%25%F0%F3%F1%F1%EA%E8%E9+english%25') == '%русский english%');

Now I'm not quite sure how to implement this in matomo tracker, but I wold try my best.

**Comment by sgiehl** [comment]
I've just checked that one. For me it seems to work as expected. Maybe that is meanwhile fixed with utf8mb4 support.

**Comment by tsteur** [comment]
Hi @KALLIAK it looks like this might be fixed. If you can still reproduce this using Matomo 4 after [migrating the DB to UTF8MB4](https://matomo.org/faq/how-to-update/how-to-convert-the-database-to-utf8mb4-charset/) then please comment here and we will be happy to reopen the issue and investigate again.

**Comment by KALLIAK** [comment]
Hi @tsteur Just tested my test.zip with the freshly installed Matomo 4.0.5 and the problem remains. 
This problem has nothing to do with the database, because the GET request to the tracker passes already corrupted keyword, i.e. the problem is in matomo.js, namely in the call "locationHrefAlias = safeDecodeWrapper(locationArray[1])". safeDecodeWrapper("%EE%EA%F0%E1") returns "îêðá", but it "must" return "окрб". When I remove "safeDecodeWrapper" and leave "locationHrefAlias = locationArray[1]", the problem goes away, but it is not a solution as far as I understand. 
But for more than a year I solve the problem this way, with each patch I have to mess with yuicompressor-2.4.8.jar, etc.)

**Comment by sgiehl** [comment]
@KALLIAK  Which browser are you using? I had tried your example, and as long as the encoding of the file is `windows-1252` and served as such it worked at least in Chrome. When you are viewing the page in your browser is the page title displayed correctly?

**Comment by KALLIAK** [comment]
We have windows-1251 encoding. We tried all famous browsers.
When I try to find "тест", I get this url: "matomotest/find.html?q=%F2%E5%F1%F2"
And then it turn to this request:
![matomo_1251_bug](https://user-images.githubusercontent.com/16630529/102762126-e4e8b000-4388-11eb-9184-1898ed305fbc.png)

**Comment by sgiehl** [comment]
Checked that again and now I was able to reproduce.

**Comment by sgiehl** [comment]
this would actually be solved with #16628

**Comment by KALLIAK** [comment]
As far as I understand, this problem will not be solved until version 6.0.0)
